version: '3'
services:
  summarizer :
    image: llmsummarizer
    build:
      context: ./

    environment :
      -  OPENAI_API_KEY=${OPENAI_API_KEY}
      - VITE_SERVER_URL='http://3.39.105.35:8090'
    ports:
      - 8090:8090

