version: '3'
services:
  summarizer :
    image: llmsummarizer
    build:
      context: ./summarizer
    ports:
      - 8090:8090
    networks:
      - my_network

  
  streamlit :
    image: llmsummarizer-streamlit
    build:
      context: ./streamlit
    ports:
      - 8502:8501
    networks: 
      - my_network
    

  
networks:
  my_network:
